[circus]
# 管理端口，HostAppStore 里的 Client 会连接这两个地址
endpoint = tcp://127.0.0.1:20771
pubsub_endpoint = tcp://127.0.0.1:20772
# 选配：如果是生产环境，可以加上统计端口
# stats_endpoint = tcp://127.0.0.1:5557
# 设置日志等级
loglevel = INFO