# dump from `ghoshell_moss.host.providers.tts_service_provider:TTSManagerConfig` 
use: volcengine_stream_tts_model
volcengine_stream_tts_model_config:
  app_key: $VOLCENGINE_STREAM_TTS_APP
  access_token: $VOLCENGINE_STREAM_TTS_ACCESS_TOKEN
  resource_id: seed-tts-2.0
  sample_rate: 44100
  audio_format: pcm
  disconnect_on_idle: 300
  disable_markdown_filter: true
  url: wss://openspeech.bytedance.com/api/v3/tts/bidirection
  speakers:
    大壹:
      tone: zh_male_dayi_saturn_bigtts
      description: 'language: (中文), support english: False, use case: 视频配音'
      voice: {}
    黑猫侦探社咪仔:
      tone: zh_female_mizai_saturn_bigtts
      description: 'language: (中文), support english: False, use case: 视频配音'
      voice: {}
    鸡汤女:
      tone: zh_female_jitangnv_saturn_bigtts
      description: 'language: (中文), support english: False, use case: 视频配音'
      voice: {}
    魅力女友:
      tone: zh_female_meilinvyou_saturn_bigtts
      description: 'language: (中文), support english: False, use case: 视频配音'
      voice: {}
    流畅女声:
      tone: zh_female_santongyongns_saturn_bigtts
      description: 'language: (中文), support english: False, use case: 视频配音'
      voice: {}
    儒雅逸辰:
      tone: zh_male_ruyayichen_saturn_bigtts
      description: 'language: (中文), support english: False, use case: 角色扮演'
      voice: {}
    可爱女生:
      tone: saturn_zh_female_keainvsheng_tob
      description: 'language: (中文), support english: False, use case: 角色扮演'
      voice: {}
    调皮公主:
      tone: saturn_zh_female_tiaopigongzhu_tob
      description: 'language: (中文), support english: False, use case: 角色扮演'
      voice: {}
    爽朗少年:
      tone: saturn_zh_male_shuanglangshaonian_tob
      description: 'language: (中文), support english: False, use case: 角色扮演'
      voice: {}
    天才同桌:
      tone: saturn_zh_male_tiancaitongzhuo_tob
      description: 'language: (中文), support english: False, use case: 角色扮演'
      voice: {}
    知性灿灿:
      tone: saturn_zh_female_cancan_tob
      description: 'language: (中文), support english: False, use case: 角色扮演'
      voice: {}
  default_speaker: 知性灿灿
